"""Calibre Username Fix

Revision ID: 7acf837791de
Revises: fda21c032e8f
Create Date: 2022-01-19 17:55:49.491079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acf837791de'
down_revision = 'fda21c032e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('calibre_usrname', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['calibre_usrname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'calibre_usrname')
    # ### end Alembic commands ###
