"""calibre_pass

Revision ID: 8e6d02abe0c5
Revises: 99b91ac7a30f
Create Date: 2021-12-02 10:47:17.443137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6d02abe0c5'
down_revision = '99b91ac7a30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibre_pass', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calibre_pass')

    # ### end Alembic commands ###
