"""admins, announcments

Revision ID: fda21c032e8f
Revises: ffd5df9c5eee
Create Date: 2021-12-09 14:49:56.906367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda21c032e8f'
down_revision = 'ffd5df9c5eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('announcment', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_column('post', 'announcment')
    # ### end Alembic commands ###
